I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/game_content/start.rpy", line 9, in script
    s sitting "You know, when the Moonpool first ran dry, I could hardly believe it."
  File "game/scripts/defines/00auto-highlight.rpy", line 102, in name_callback
    renpy.sound.play(ticksfile)
NameError: name 'ticksfile' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/game_content/start.rpy", line 9, in script
    s sitting "You know, when the Moonpool first ran dry, I could hardly believe it."
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 621, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\character.py", line 1455, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\character.py", line 1106, in do_display
    display_say(who,
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\character.py", line 797, in display_say
    pause_callback("show_done")
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\character.py", line 91, in __call__
    c(*args, **kwargs)
  File "game/scripts/defines/00auto-highlight.rpy", line 102, in name_callback
    renpy.sound.play(ticksfile)
NameError: name 'ticksfile' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
 1.0
Thu Feb 13 18:44:20 2025
