I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/game_content/burial_site.rpy", line 407, in script
    if quest_favorite_prey.cancelled or quest_favorite_prey.failed:
  File "game/scripts/game_content/burial_site.rpy", line 407, in <module>
    if quest_favorite_prey.cancelled or quest_favorite_prey.failed:
AttributeError: 'Quest' object has no attribute 'failed'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/game_content/burial_site.rpy", line 407, in script
    if quest_favorite_prey.cancelled or quest_favorite_prey.failed:
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 1849, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/scripts/game_content/burial_site.rpy", line 407, in <module>
    if quest_favorite_prey.cancelled or quest_favorite_prey.failed:
AttributeError: 'Quest' object has no attribute 'failed'

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
 1.0
Sun Mar 30 16:50:44 2025
